### ISSUE TITLE
Support Backbone.PageableCollection

### ISSUE THREAD

**Issue by oosterholt** [p3drosola/Backbone.VirtualCollection#58]
It would be nice if Backbone.VirtualCollection would support [Backbone.PageableCollection](https://github.com/backbone-paginator/backbone.paginator).

Virtual collections are great and we use them a lot. But when collections are getting larger, the user might profit from pageable collections.

**Comment by p3drosola** [comment]
Hi @oosterholt,
Can you explain a little more about your use case? 

I haven't used Backbone.PageableCollection before but their docs state:

> Backbone.PageableCollection is a strict superset of Backbone.Collection and passes its test suite.

So you should be able to use a PageableCollection as the parent collection.

**Comment by p3drosola** [comment]
Closing this issue since there hasn't been an update.

**Comment by oosterholt** [comment]
Agreed. I asked a coworker to wrap up our problem in a nice scenario. 
He did not contacted me yet.
I'll add our use case as soon as possible.

**Comment by ambischof** [comment]
Since no one else has posted a use case and I believe these two libraries would compliment each other, I'll explain it a little. Be warned I've never actually used Virtual Collection, just Pageable Collection. I'm also not sure if it should be VirtualCollection supporting PageableCollection or the other way around.

In order for everything to work correctly, the virtual collection would have to be the parent of the PageableCollection because you're not trying to take page 2 of the full collection, but the filtered collection. I'll try an example. Say I have 50 users in my collection, and I filter for guys named "Sam", removing 44 users, and I'm on page 2 with 10 items per page. If the paginated collection is the parent, then the virtual collection will only filter the items on page 2, so you're essentially searching only page 2 for Sams instead of the entire collection.
